specfile_path: beaker.spec

notifications:
  pull_request:
    successful_build: false

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
      - epel-7-x86_64
      - epel-8-x86_64
      - fedora-31-x86_64
      - fedora-32-x86_64
      - fedora-33-x86_64
      - fedora-rawhide-x86_64
      - centos-stream-x86_64
