dist: bionic
language: python
python: '3.7'
os: linux

addons:
  apt:
    packages:
      - cpu-checker
      - qemu-kvm
      - libvirt-bin
      - virtinst
      - bridge-utils
      - libguestfs-tools

jobs:
  fast_finish: false
  include:
    - before_install: ./Misc/travis.sh before_install
      install: ./Misc/travis.sh install
      script: ./Misc/travis.sh script
      name: Client tests
      env: EXEC_TESTS=bkr.inttest.client
    - before_install: ./Misc/travis.sh before_install
      install: ./Misc/travis.sh install
      script: ./Misc/travis.sh script
      name: Lab controller tests
      env: EXEC_TESTS=bkr.inttest.labcontroller
    - before_install: ./Misc/travis.sh before_install
      install: ./Misc/travis.sh install
      script: ./Misc/travis.sh script
      name: Server tests
      env: EXEC_TESTS=bkr.inttest.server