dist: bionic
language: python
python: '3.7'
os: linux

addons:
  apt:
    packages:
      - cpu-checker
      - qemu-kvm
      - libvirt-bin
      - virtinst
      - bridge-utils
      - libguestfs-tools

before_install: ./Misc/travis.sh before_install

install: ./Misc/travis.sh install
