name: Review-checks

on: [pull_request]

jobs:
  check-docs:
    runs-on: ubuntu-latest
    container:
      image: centos:8

    steps:
    - uses: actions/checkout@v1
    - name: Install utils
      run: |
        yum install -y git wget
    - name: Fetch Beaker repository
      run: |
        wget https://beaker-project.org/yum/beaker-server-RedHatEnterpriseLinux.repo -P /etc/yum.repos.d/
    - name: Install Beaker dependency from specfile
      run: |
        yum-builddep *.spec -y
    - name: Build documentation
      run: |
        make -C documentation html SPHINXOPTS="-W"
        mv documentation/_build/html /__w
    - uses: actions/upload-artifact@v1
      with:
        name: beaker-docs
        path: /home/runner/work/html

